DIAGNOSTICS = (
    # Risk 0
    ["NORM"]
    # Risk 1
    + [
        "SEHYP",
        "RVH",
        "LPFB",
        "RAO/RAE",
        "ILBBB",
        "ISCLA",
        "LAO/LAE",
        "1AVB",
        "ISC_",
        "CRBBB",
        "NST_",
        "IRBBB",
        "LAFB",
        "NDT",
    ]
    # Risk 2
    + [
        "INJIN",
        "INJLA",
        "INJIL",
        "2AVB",
        "ISCAN",
        "DIG",
        "EL",
        "ISCIL",
        "ISCIN",
        "ISCAS",
        "INJAS",
        "IVCD",
        "ISCAL",
        "CLBBB",
        "LVH",
    ]
    # Risk 3
    + [
        "ANEUR",
        "3AVB",
        "PMI",
        "IPMI",
        "INJAL",
        "IPLMI",
        "LMI",
        "WPW",
        "LNGQT",
        "ALMI",
        "AMI",
        "ILMI",
        "ASMI",
        "IMI",
    ]
)

SUB2SUPER = {
    "NORM": "NORM",
    "LAFB/LPFB": "CD",
    "IRBBB": "CD",
    "ILBBB": "CD",
    "CLBBB": "CD",
    "CRBBB": "CD",
    "_AVB": "CD",
    "IVCD": "CD",
    "WPW": "CD",
    "LVH": "HYP",
    "RVH": "HYP",
    "LAO/LAE": "HYP",
    "RAO/RAE": "HYP",
    "SEHYP": "HYP",
    "AMI": "MI",
    "IMI": "MI",
    "LMI": "MI",
    "PMI": "MI",
    "ISCA": "STTC",
    "ISCI": "STTC",
    "ISC_": "STTC",
    "NST_": "STTC",
    "STTC": "STTC",
}

DIAG2SUB = {
    "LAFB": "LAFB/LPFB",
    "IRBBB": "IRBBB",
    "1AVB": "_AVB",
    "IVCD": "IVCD",
    "CRBBB": "CRBBB",
    "CLBBB": "CLBBB",
    "LPFB": "LAFB/LPFB",
    "WPW": "WPW",
    "ILBBB": "ILBBB",
    "3AVB": "_AVB",
    "2AVB": "_AVB",
    "LVH": "LVH",
    "LAO/LAE": "LAO/LAE",
    "RVH": "RVH",
    "RAO/RAE": "RAO/RAE",
    "SEHYP": "SEHYP",
    "IMI": "IMI",
    "ASMI": "AMI",
    "ILMI": "IMI",
    "AMI": "AMI",
    "ALMI": "AMI",
    "INJAS": "AMI",
    "LMI": "LMI",
    "INJAL": "AMI",
    "IPLMI": "IMI",
    "IPMI": "IMI",
    "INJIN": "IMI",
    "PMI": "PMI",
    "INJLA": "AMI",
    "INJIL": "IMI",
    "NORM": "NORM",
    "NDT": "STTC",
    "NST_": "NST_",
    "DIG": "STTC",
    "LNGQT": "STTC",
    "ISC_": "ISC_",
    "ISCAL": "ISCA",
    "ISCIN": "ISCI",
    "ISCIL": "ISCI",
    "ISCAS": "ISCA",
    "ISCLA": "ISCA",
    "ANEUR": "STTC",
    "EL": "STTC",
    "ISCAN": "ISCA",
}

FORM = [
    "NDT",
    "NST_",
    "DIG",
    "LNGQT",
    "ABQRS",
    "PVC",
    "STD_",
    "VCLVH",
    "QWAVE",
    "LOWT",
    "NT_",
    "PAC",
    "LPR",
    "INVT",
    "LVOLT",
    "HVOLT",
    "TAB_",
    "STE_",
    "PRC(S)",
]


RHYTHM = [
    "SR",
    "AFIB",
    "STACH",
    "SARRH",
    "SBRAD",
    "PACE",
    "SVARR",
    "BIGU",
    "AFLT",
    "SVTAC",
    "PSVT",
    "TRIGU",
]
